### ISSUE TITLE
Serving images in next-gen formats

### ISSUE THREAD

**Issue by VenkataBhaskarr** [virtual-tech-school/virtual-tech-school#10]
As our application is not performing well in image rendering as suggested by page speed insights, to improve the performance of the application the images should be served in next-gen formats.

So converting all the images in assets folder (.png and .svg ) to webP format would resolve the problem.

**Comment by apoorv-on-git** [comment]
Could you take up this issue? Post a screenshot of the site performance after your changes. :)

**Comment by VenkataBhaskarr** [comment]
yeah, I will work on this
