### ISSUE TITLE
Direct links to socials instead of retrieving them as environment variables

### ISSUE THREAD

**Issue by VenkataBhaskarr** [virtual-tech-school/virtual-tech-school#4]
In home page, join us today section when we are clicking the join buttons of the socials its redirecting to a not found url because we are retrieving the links from environment variables.

So instead of retrieving them from environment variables can't we add direct links?

<img width="649" alt="Screenshot 2022-12-24 at 3 20 14 PM" src="https://user-images.githubusercontent.com/111889155/209468317-8ba8f8b8-75da-41d4-99e4-4613a79e08a7.png">

Here  link of YouTube channel was added directly instead of retrieving from environment variable as in the case of Discord link.

**Comment by apoorv-on-git** [comment]
Sounds like a fair issue @VenkataBhaskarr. Feel free to raise a PR for the same. :)

**Comment by apoorv-on-git** [comment]
I've assigned this issue to you @VenkataBhaskarr.
